name: erpnext
services:

  web:
    image: ghcr.io/marcag3/erpnext-custom:latest
    platform: linux/amd64
    environment:
      DB_HOST: db
      DB_PORT: 3306
      SOCKETIO_PORT: 9000
      DB_PASSWORD: "${DB_PASSWORD}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      AUTORUN_ENABLED: "true"
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites/frontend
    ports:
      - "8080:80"  # Nginx will proxy to gunicorn on 8000 and websocket on 9000
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
    networks:
      # home-server_proxy:
      default:
      

  queue:
    image: ghcr.io/marcag3/erpnext-custom:latest
    platform: linux/amd64
    command: ["bench", "worker", "--queue", "long,default,short"]
    stop_signal: SIGTERM
    environment:
      DB_HOST: db
      DB_PORT: 3306
      REDIS_CACHE: redis-cache
      REDIS_QUEUE: redis-queue
      DB_PASSWORD: "${DB_PASSWORD}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      AUTORUN_ENABLED: "false"
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites/frontend
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy


  scheduler:
    image: ghcr.io/marcag3/erpnext-custom:latest
    platform: linux/amd64
    command: ["bench", "schedule"]
    stop_signal: SIGTERM
    environment:
      DB_HOST: db
      DB_PORT: 3306
      REDIS_CACHE: redis-cache
      REDIS_QUEUE: redis-queue
      DB_PASSWORD: "${DB_PASSWORD}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      AUTORUN_ENABLED: "false"
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites/frontend
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy

  db:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    volumes:
      - ./db-data:/var/lib/mysql


  redis-cache:
    image: redis:7.4-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 3s
    volumes:
      - type: volume
        source: redis-cache-data
        target: /data
        volume: {}

  redis-queue:
    image: redis:7.4-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 3s
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}


networks:
  default:
    name: erpnext
  # home-server_proxy:
  #   external: true
volumes:
  redis-cache-data:
    name: frappe_docker_redis-cache-data
  redis-queue-data:
    name: frappe_docker_redis-queue-data