name: erpnext
services:

  web:
    image: ghcr.io/marcag3/erpnext-custom:main
    platform: linux/amd64
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: 9000
      DB_PASSWORD: "${DB_PASSWORD}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}"
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
    ports:
      - "8080:80"  # Nginx will proxy to gunicorn on 8000 and websocket on 9000
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
    networks:
      home-server_proxy:
      default:

  db:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/mysql

  queue:
    image: ghcr.io/marcag3/erpnext-custom:main
    platform: linux/amd64
    restart: unless-stopped
    command: ["bench", "worker", "--queue", "long,default,short"]
    stop_signal: SIGTERM
    environment:
      DB_HOST: db
      DB_PORT: 3306
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy

  redis-cache:
    image: redis:6.2-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 3s
    volumes:
      - type: volume
        source: redis-cache-data
        target: /data
        volume: {}

  redis-queue:
    image: redis:6.2-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 3s
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}

  scheduler:
    image: ghcr.io/marcag3/erpnext-custom:main
    platform: linux/amd64
    restart: unless-stopped
    command: ["bench", "schedule"]
    stop_signal: SIGTERM
    environment:
      DB_HOST: db
      DB_PORT: 3306
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy

networks:
  default:
    name: erpnext
  home-server_proxy:
    external: true
volumes:
  redis-cache-data:
    name: frappe_docker_redis-cache-data
  redis-queue-data:
    name: frappe_docker_redis-queue-data