name: Build and Push Custom ERPNext Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Weekly build on Monday at midnight
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Generate APPS_JSON_BASE64
      id: apps_json
      run: |
        APPS_JSON=$(cat apps.json)
        echo "::set-output name=apps_json_base64::$(echo $APPS_JSON | base64 -w 0)"

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: src/variations/erpnext-nginx/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          APPS_JSON_BASE64=${{ steps.apps_json.outputs.apps_json_base64 }}

